name: magic-transcript
region: sfo3
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: .
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        value: "737482c1ddf734d660222fb4810a0a99b7b777655c3324f7dd2188e9cb34cfef"
    routes:
      - path: /
